### ISSUE TITLE
Create and populate wallet-to-wallet table

### ISSUE THREAD

**Issue by boshmaf** [cibr-qcri/airflow-tasks#2]
Part of a multi-issue task: cibr-qcri/airflow-tasks#2, cibr-qcri/toshi#22

Table schema:
- first_cluster (varchar)
- second_cluster (varchar)
- num_txes_to_second (integer)
- num_txes_from_second (integer)
- first_cluster_size (integer)
- second_cluster_size (integer)
- total_satoshi_to_second (biginteger)
- total_satoshi_from_second (biginteger)
- total_usd_to_second (numeric)
- total_usd_from_second (numeric)

**Comment by sajithaliyanage** [comment]
Related commit: https://github.com/cibr-qcri/airflow-tasks/commit/f6b3b42ce3d80e3466e63b15f78e90b5275cba96

**Comment by boshmaf** [comment]
Turns out creating this labels take too much memory (didn't work on 96GB node, and started swapping). For example, for block height 340K, there are more than 350M edges, and for each edge we need to aggregate tx data. A better way to do this is to query in real-time using a graph DB like Arango (if optimized) or pre-compute it using Apache Spark.

For now, we're going to try real-time querying using Arango in prod. For dev, it takes 1 min max for some queries, so we expect issues if Arango is not optimized. If Arango does scale, we have to reopen and work on pre-computed Spark (or a better real-time graph DB).
