### ISSUE TITLE
Implement an Airflow task to run MantiCore across all DeFi contracts

### ISSUE THREAD

**Issue by boshmaf** [cibr-qcri/airflow-tasks#27]

**Comment by thedarkspy** [comment]
It seems that it is not practical to use MantiCore for analyzing all contracts as it's average execution time per contract is over 15 minutes. What we can do instead is to create a special service that analyzes contracts on demand and return the result of the scanner by email for example then update the entry in the database.

**Comment by boshmaf** [comment]
Closing due to inefficient scanning.
