### ISSUE TITLE
Update GP init task to create two new columns "timestamp" and "notes" for address_label data table

### ISSUE THREAD

**Issue by boshmaf** [cibr-qcri/airflow-tasks#3]

**Comment by sajithaliyanage** [comment]
Related commit: https://github.com/cibr-qcri/airflow-tasks/commit/ca5b367e7486c5edb747d4ec32efa8787152af29#diff-190e3fd97d2aafc2e73267e11d3509ddb22505d3c8a224dac66f7230e316f763R8
