### ISSUE TITLE
Implement an Airflow task to compute top linked contracts

### ISSUE THREAD

**Issue by thedarkspy** [cibr-qcri/airflow-tasks#35]
Depends on cibr-qcri/airflow-tasks#34

Use the contract call graph to find all contracts that calls a given contract or the given contract calls. After that, get the top 5 in terms of from/to calls. Save the result for each given contract as a datatable in GP.

**Comment by boshmaf** [comment]
Couldn't precompute the links aggregation (combine same edges into one and increase their count). Closing for now.
