### ISSUE TITLE
Move all scripts into their own tasks and separate their functionality

### ISSUE THREAD

**Issue by boshmaf** [cibr-qcri/airflow-tasks#4]

**Comment by sajithaliyanage** [comment]
Related Commits:
https://github.com/cibr-qcri/airflow-tasks/commit/0b29920e1468d4d5d53467f0f18dcfec6ef9dfd8
https://github.com/cibr-qcri/airflow-tasks/commit/ed54b5a54b6d0b2538001f738249e59f7ec0a319
https://github.com/cibr-qcri/airflow-tasks/commit/f0115f9b80008fbf8dcfcd89744eb09a92507b5d
https://github.com/cibr-qcri/airflow-tasks/commit/ca5b367e7486c5edb747d4ec32efa8787152af29
https://github.com/cibr-qcri/airflow-tasks/commit/6664c0767fca2341690adc57d8d6765af48abfa5
