### ISSUE TITLE
Implement an Airflow task to disassemble EVM bytecode across all contracts with symbol and name

### ISSUE THREAD

**Issue by boshmaf** [cibr-qcri/airflow-tasks#40]
https://github.com/crytic/pyevmasm
https://github.com/tintinweb/ethereum-dasm
https://github.com/Arachnid/evmdis

**Comment by sajithaliyanage** [comment]
Related Commit: https://github.com/cibr-qcri/airflow-tasks/commit/a915c284c3daa1c91b19587b32ca03936879e207
