### ISSUE TITLE
Update the default value of risk score in the wallet data table to -1

### ISSUE THREAD

**Issue by boshmaf** [cibr-qcri/airflow-tasks#6]
Part of a multi-issue task: cibr-qcri/airflow-tasks#6, cibr-qcri/toshi#15

Depends on cibr-qcri/airflow-tasks#4

**Comment by sajithaliyanage** [comment]
Related commit: https://github.com/cibr-qcri/airflow-tasks/commit/ed54b5a54b6d0b2538001f738249e59f7ec0a319#diff-6323377596ed2b6967670710e2fab5af9ef91c374c69e14fdd2d2fb887a8830eR20
