### ISSUE TITLE
Implement new Airflow tasks for on-demand bytecode scanning

### ISSUE THREAD

**Issue by boshmaf** [cibr-qcri/airflow-tasks#75]
Initial:
- Check if address is valid (against eth_contract_table). If valid, proceed with scanning. Otherwise, job fails.
- Check if address is valid on etherscan. If valid, update all GB tables with etherscan data for the new contract and then proceed with scanning. If not, job fails.

Scanning:
- Run 5 parallel scanning tasks, one for each scanner.

Parsing:
- Once scan results are done (scanning is done), parse and generate vulnerabilities

Scoring:
- Calculate security score for contract

**Comment by sajithaliyanage** [comment]
To deal with the Etherscan API quota, we want to implement an API gateway to deal with the quota issue instead of exiting random sleep mechanism

**Comment by sajithaliyanage** [comment]
We have faced an issue on Airflow, the scheduler does not schedule dag tasks in the Kubernetes cluster when we trigger a Dag using their REST API. Still, we are doing an investigation to find out the root cause of this. Currently, we suspect that this happens due to the resource limitation in the K8s cluster.

**Comment by sajithaliyanage** [comment]
Related Commits:
- https://github.com/cibr-qcri/airflow-tasks/commit/342d750124cd3a406b090738ca0701f5a73e9d18
- https://github.com/cibr-qcri/airflow-tasks/commit/5cb968e2b995de3c2efd72dcd7b2654043f9ebf8
- https://github.com/cibr-qcri/airflow-tasks/commit/ad8cfa826c8c25309900970b601584d6d72b391b
- https://github.com/cibr-qcri/airflow-tasks/commit/8ee3a0a37e64d1b320933221481b3419e06795b0
- https://github.com/cibr-qcri/airflow-tasks/commit/351b6820bd97481c656c40fa2dda7eab4b903ff5
- https://github.com/cibr-qcri/airflow-tasks/commit/5fbce630a2cb962f6ec59cfe2a2f5d91c6fd72d6
- https://github.com/cibr-qcri/airflow-tasks/commit/51314c56e68dea26009d5d41b701c29117d5e02d
- https://github.com/cibr-qcri/airflow-tasks/commit/f06f28cc7ab9276701bd574d7a3fad4981cbd550
- https://github.com/cibr-qcri/airflow-tasks/commit/a970800e83b7f9b3cbe05c639a32a18d571f916d
